name: Major Version Updater
# Whenever a new release is made, push a major version tag
on:
  release:
    types: [ published ]

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get major version num and update tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        MAJOR=${VERSION%%.*}
        git config --global user.name 'Kitty Chiu'
        git config --global user.email '42864823+KittyChiu@users.noreply.github.com'
        git tag -fa ${MAJOR} -m "Update major version tag"
        git push origin ${MAJOR} --force
